Repository ChoraClub/chora_club, pull requests merged in 2025-02, with the labels that each got.

#44 Improve CC Score Calculation & Fix Ranking Display for Sorting/Search
  src/app/api/getleaderboard/[dao]/route.ts
  src/components/IndividualDAO/Leaderboard.tsx
  src/components/Proposals/ProposalMain.tsx
Labels: enhancement

#35 Add Redis Cache Mechanism for Profile Page and Recorded Sessions
  src/app/api/get-office-hours/route.ts
Labels: enhancement

#47 Bug Fix: Invalidate Redis Cache for Office Hours to Ensure Fresh Data
  src/app/api/edit-office-hours/route.ts
  src/app/api/get-office-hours/route.ts
Labels: bug

#49 Fix Bug: Invalidate Redis Keys for Office Hours, User Profile, and Meetings
  src/app/api/attest-offchain/route.ts
  src/app/api/edit-office-hours/route.ts
  src/app/api/office-hours/route.ts
  src/app/api/update-recorded-session/route.ts
Labels: bug

#50 Fix: UI Duplication and UI Enhancements
  src/app/(routes)/[daoDelegates]/page.tsx
  src/app/(routes)/explore-daos/page.tsx
  src/app/(routes)/notifications/page.tsx
  src/app/(routes)/office-hours/page.tsx
  src/components/ComponentUtils/ConnectYourWallet.tsx
  src/components/ComponentUtils/OfficeHourTile.tsx
  src/components/IndividualDelegate/SpecificDelegate.tsx
  src/components/UserProfile/InstantMeet.tsx
  src/components/WalletWrapper.tsx
  src/components/WatchMeeting/WatchLeaderBoard.tsx
  src/components/WatchMeeting/WatchSession.module.css
  src/components/WatchMeeting/WatchSession.tsx
Labels: bug

#51 Correct Component Name
  src/app/(routes)/explore-daos/page.tsx
Labels: bug

#52 Improve button styles and implement conditional rendering in DelegateTileModal
  src/components/Alert/Alert.tsx
  src/components/ComponentUtils/DelegateTileModal.tsx
  src/components/IndividualDAO/DelegatesSession.tsx
  src/components/IndividualDAO/OfficeHours.tsx
  src/components/IndividualDelegate/DelegateInfo.tsx
  src/components/IndividualDelegate/DelegateOfficeHrs.tsx
  src/components/IndividualDelegate/DelegateSessions.tsx
  src/components/OfficeHours/DaoOfficeHours.tsx
  src/components/UserProfile/UserAllOfficeHrs/UserScheduledHours.tsx
  src/components/UserProfile/UserInfo.tsx
  src/components/UserProfile/UserOfficeHours.tsx
  src/components/UserProfile/UserSessions.tsx
Labels: enhancement

#53 Enhanced User Experience Across Multiple Pages
  src/components/ClaimReward/TotalRewards.tsx
  src/components/DAOs/ExploreDAOs.tsx
  src/components/DelegateSessions/DelegateSessionsMain.tsx
  src/components/IndividualDAO/DelegatesList.tsx
  src/components/IndividualDAO/DelegatesSession.tsx
  src/components/IndividualDAO/OfficeHours.tsx
  src/components/Referrals/InviteCreators.tsx
  tailwind.config.ts
Labels: bug, enhancement

#54 Office Hours Notification and huddle API upgradation
  src/app/api/create-room/route.ts
  src/app/api/delete-office-hours/route.ts
  src/app/api/edit-office-hours/route.ts
  src/app/api/get-room/route.ts
  src/app/api/office-hours/route.ts
  src/components/ComponentUtils/DeleteOfficeHoursModal.tsx
  src/components/IndividualDelegate/AllSessions/BookSession.tsx
  src/components/Notification/NotificationActions.tsx
  src/components/Notification/NotificationMain.tsx
  src/components/Notification/OfficeHours.tsx
  src/components/UserProfile/UserOfficeHours.tsx
  src/components/UserProfile/UserSessions.tsx
  src/middleware.ts
Labels: enhancement

#55 Enhance UI and functionality across scheduled sessions, claim rewards, office hours, recorded sessions, and profile pages with optimized APIs and improved design.
  src/app/api/get-recorded-meetings/route.ts
  src/components/ClaimReward/MintedNFTs.tsx
  src/components/ClaimReward/NFTTile.tsx
  src/components/ComponentUtils/StatesGrid.tsx
  src/components/DelegateSessions/RecordedSessions.tsx
  src/components/IndividualDelegate/DelegateInfo.tsx
  src/components/OfficeHours/DaoOfficeHours.tsx
  src/components/UserProfile/UserAllSessions/ScheduledUserSessions.tsx
  src/components/UserProfile/UserInfo.tsx
Labels: bug, enhancement

#57 Remove office-hours key due to some runtime bug.
  src/app/api/delete-office-hours/route.ts
  src/app/api/edit-office-hours/route.ts
  src/app/api/office-hours/route.ts
  src/utils/cacheWrapper.ts
Labels: bug
